travis:
  secure:
    BINSTAR_TOKEN: nJXeYa//ByS50YtAo0saLdXZUQ5+oFxyO54Y6qxciSkVkKWZCqYto7b2JY4qz27fvuWVmt2UuR1o5C5zlWQdzVXrJIahi7CPGfc0+ZAOhTlsVYmFN9LmWwMuRXFnRfWao9Q+Wv2k+KN4YH/qRW53DvBJ20mmEuZttqWFo7jQfao8sjQB01xa1zfT9AgGc0z0V9IMHSXgtVSkYrjK8M5deXTWpq2iJ6dB5vd9uag1piiKwGmyUui3D68CL1niF81D2Rku3Rm0Sk7eCxLp3VBstV+T66IkfAX1b+4BJkKSzUJ7a+OhWngN5tUFAvtAEWpv0prr6TXnhKiIQxCthrnq7+XO5b+xPXnFjwk0VIyctDXS3i0MI6XHezBLe5fXyOksXtoXCT7HakPqd3dku90LAvZqAD4st5yxUNRtobMI1IZ6C+lrsJLOxKu1Xs40iQLuAvNEsSPvOGw/tcjU6i5qnbjNOXq8mURykVw0Uya54CmcJJ/kOqNtMULfyi2PRZ8ymnxmsUxrKydqVzVk5ZqWcvhlGVBNFxuTQ0Y10w2/AGKvzngrlMqxJfU1Ehozd9ak8TriLJakQzctwlw4rnHlGHYWWl/nFN8gRZmHfckbhxHCZ2qV2SK3ZoEXYOV/qhDEyUB+Y/yfs5WDtCvF1WM/LdmzYbsbXRS+dkad8OFnOaM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
